/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajeroautomatico;

import cajeroautomatico.constantes.Constantes;
import cajeroautomatico.entities.Cliente;
import cajeroautomatico.http.AutenticacionTask;
import cajeroautomatico.http.EdicionSaldoClienteTask;
import cajeroautomatico.http.SaldoClienteTask;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenny
 */
public class FormSeleccionMonto extends javax.swing.JFrame {
    private Cliente clienteSeleccionado = new Cliente();

    /**
     * Creates new form FormSeleccionMonto
     */
    public FormSeleccionMonto() {
        initComponents();
    }

    /**
     * Creates new form TipoOperacion
     */
    public FormSeleccionMonto(Cliente cliente) {
        initComponents();
        this.clienteSeleccionado = cliente;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        etMonto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tvContinuarRetiro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 70, 140, 30);

        etMonto.setEditable(false);
        etMonto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        etMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(etMonto);
        etMonto.setBounds(180, 180, 130, 40);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 140, 140, 30);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 270, 170, 30);

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 70, 150, 30);

        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 140, 150, 30);

        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7);
        jLabel7.setBounds(350, 200, 140, 30);

        tvContinuarRetiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvContinuarRetiroMouseClicked(evt);
            }
        });
        jPanel1.add(tvContinuarRetiro);
        tvContinuarRetiro.setBounds(320, 270, 170, 30);

        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 200, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg_monto_retiro.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-9, -4, 500, 318);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here: 
        etMonto.setText("20");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        etMonto.setText("40");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        new TipoOperacion().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        etMonto.setText("100");
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        etMonto.setText("200");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        etMonto.setText("400");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void tvContinuarRetiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvContinuarRetiroMouseClicked
        // TODO add your handling code here: 
        // si es vacío, entonces no saltamos a la siguiente ventana..
        if(etMonto.getText().toString().length() == 0)
            return;
         
        // recuperamos el saldo actual del momento.. por seguridad
        new SaldoClienteTask(clienteSeleccionado, new SaldoClienteTask.OnResult() {
            @Override
            public void onResult(int codResultado, String message, Cliente cliente) {
                if(codResultado == Constantes.RESULT_ERROR)
                {
                    JOptionPane.showMessageDialog(null, message);
                    return;
                } 
                double montoRetiro = Double.valueOf(etMonto.getText()); 
                if(cliente.getSaldo() < montoRetiro )
                {
                    new FormSaldoInsuficiente(cliente).setVisible(true);
                    dispose();
                }
                else
                {
                    double saldoFinal = (cliente.getSaldo() - montoRetiro);
                    String saldoFinalFormateado = String.format(Locale.getDefault(), "%.2f", saldoFinal);
                    clienteSeleccionado.setSaldo(saldoFinal);
                    // RETIRAR EFECTIVO, ACTUALIZAR SALDO USUARIO
                    new EdicionSaldoClienteTask(clienteSeleccionado, saldoFinalFormateado, new EdicionSaldoClienteTask.OnResult() {
                        @Override
                        public void onResult(int codResultado, String message, Cliente cliente) { 
                            if(codResultado == Constantes.RESULT_ERROR)
                            {
                                JOptionPane.showMessageDialog(null, message);
                                return;
                            } 
                            new FormRetiroEfectivo(clienteSeleccionado, etMonto.getText()).setVisible(true);
                            dispose(); 
                        }
                    }).execute();
                }
                
            }
        }).execute();  
        
    }//GEN-LAST:event_tvContinuarRetiroMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        etMonto.setText("60");
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSeleccionMonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSeleccionMonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSeleccionMonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSeleccionMonto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSeleccionMonto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField etMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tvContinuarRetiro;
    // End of variables declaration//GEN-END:variables
}
